/*
	任务提示文本
*/
#define TEXT_FAILED_DESTORY "~r~ You have destroyed the vehicle."
#define TEXT_FAILED_LEFT "~r~ You have left the vehicle."
#define TEXT_FAILED_DEAD "~r~ You dead."
#define TEXT_MISSION_DRIVE_FAST "Drive this car as fast as possible."
#define TEXT_MISSION_DRIVE_SLOW "Drive this car as slowly as possible."
#define TEXT_MISSION_OBECTIVE "Take the ~y~vehicle~w~ on a test drive."
#define TEXT_MISSION_NOWORK "Sorry there is no work for you right now ~n~please come back later!"
#define TEXT_MISSION_DRIVE_2SLOW "~w~ You drive too slow."
#define TEXT_MISSION_DRIVE_2FAST "~w~ You drive too fast."