/*
	任务提示文本
*/
#define TEXT_FAILED_DESTORY "~r~ 你把试驾车给爆了."
#define TEXT_FAILED_LEFT "~r~ 你离开了试驾车辆."
#define TEXT_FAILED_DEAD "~r~ 你挂了."
#define TEXT_MISSION_DRIVE_FAST "尽可能的开快这个车，越快越好."
#define TEXT_MISSION_DRIVE_SLOW "尽可能的平稳驾驶这车."
#define TEXT_MISSION_OBECTIVE "请上~y~试驾车辆~w~"
#define TEXT_MISSION_NOWORK "不好意思，目前本车行没用可以给你的工作，请稍后再来！"
#define TEXT_MISSION_DRIVE_2SLOW "~w~ 你开的太慢了！"
#define TEXT_MISSION_DRIVE_2FAST "~w~ 你开的太快了！"
#define TEXT_MISSION_DRIVE_BACK "把车开回~r~卖车行"